# Generated by Django 5.2.4 on 2025-08-17 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='project_detail',
            name='project_document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='project_document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_detail',
            name='project_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='project_files'),
            preserve_default=False,
        ),
    ]
