# Generated by Django 5.2.4 on 2025-08-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_detail',
            name='purchased',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
