# Generated by Django 5.2.4 on 2025-09-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_project_detail_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_detail',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
