# Generated by Django 5.2.4 on 2025-08-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_custom_user_groups_custom_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
