# Generated by Django 5.2.4 on 2025-08-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_custom_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
