# Generated by Django 5.2.4 on 2025-08-15 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_custom_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='token',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
