# Generated by Django 5.2.4 on 2025-09-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_custom_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='userpicture/'),
        ),
    ]
