# Generated by Django 5.2.4 on 2025-08-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payu_payment_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
